Algoritmo "funcao_soma_ex95"

Var
    valor1, valor2, Adicao: inteiro
Funcao Soma(X, Y: inteiro):inteiro
inicio
    retorne X + Y
fimFuncao

Inicio
     Escreva("Digite o primeiro valor: ")
     leia(valor1)
     Escreva("Digite o segundo valor: ")
     leia(valor2)
     Adicao <- Soma(valor1,valor2)
     Escreval("A soma entre ", valor1, " e ", valor2, " é igual", Adicao)

Fimalgoritmo