Algoritmo "calculaIdade"

Var

    ano, nasc, idade: inteiro

Inicio
      escreva("Em que ano nós estamos? ")
      leia(ano)
      escreva("Em que ano você nasceu? ")
      leia(nasc)
      idade <- ano - nasc
      
      escreva("Em ", ano, " você terar ", idade, " anos")
      
      se(idade >= 21)entao
         escreval("e já tera atingido a maioridade")
      FimSe
      


Fimalgoritmo